// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lib_repositorios.Implementaciones;

#nullable disable

namespace lib_repositorios.Migrations
{
    [DbContext(typeof(Conexion))]
    [Migration("20251104000414_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("lib_dominio.Entidades.Auditorias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdRegistroAfectado")
                        .HasColumnType("int");

                    b.Property<string>("TablaAfectada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Usuario")
                        .HasColumnType("int");

                    b.Property<int?>("_UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("_UsuarioId");

                    b.ToTable("Auditorias");
                });

            modelBuilder.Entity("lib_dominio.Entidades.Clientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("lib_dominio.Entidades.Empleados", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("lib_dominio.Entidades.Fincas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Fincas");
                });

            modelBuilder.Entity("lib_dominio.Entidades.Inventarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Finca")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("_FincaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("_FincaId");

                    b.ToTable("Inventarios");
                });

            modelBuilder.Entity("lib_dominio.Entidades.Mantenimientos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Finca")
                        .HasColumnType("int");

                    b.Property<string>("Responsable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("_FincaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("_FincaId");

                    b.ToTable("Mantenimientos");
                });

            modelBuilder.Entity("lib_dominio.Entidades.Pagos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechadePago")
                        .HasColumnType("datetime2");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Reserva")
                        .HasColumnType("int");

                    b.Property<int?>("_ReservaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("_ReservaId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("lib_dominio.Entidades.Promociones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Promociones");
                });

            modelBuilder.Entity("lib_dominio.Entidades.ReservaPromociones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Promocion")
                        .HasColumnType("int");

                    b.Property<int>("Reserva")
                        .HasColumnType("int");

                    b.Property<int?>("_PromocionId")
                        .HasColumnType("int");

                    b.Property<int?>("_ReservaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("_PromocionId");

                    b.HasIndex("_ReservaId");

                    b.ToTable("ReservaPromociones");
                });

            modelBuilder.Entity("lib_dominio.Entidades.ReservaServicios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("Reserva")
                        .HasColumnType("int");

                    b.Property<int>("Servicio")
                        .HasColumnType("int");

                    b.Property<int?>("_ReservaId")
                        .HasColumnType("int");

                    b.Property<int?>("_ServicioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("_ReservaId");

                    b.HasIndex("_ServicioId");

                    b.ToTable("ReservaServicios");
                });

            modelBuilder.Entity("lib_dominio.Entidades.Reservas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cliente")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("Finca")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("_ClienteId")
                        .HasColumnType("int");

                    b.Property<int?>("_FincaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("_ClienteId");

                    b.HasIndex("_FincaId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("lib_dominio.Entidades.Reseñas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calificacion")
                        .HasColumnType("int");

                    b.Property<int>("Cliente")
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Finca")
                        .HasColumnType("int");

                    b.Property<int?>("_ClienteId")
                        .HasColumnType("int");

                    b.Property<int?>("_FincaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("_ClienteId");

                    b.HasIndex("_FincaId");

                    b.ToTable("Reseñas");
                });

            modelBuilder.Entity("lib_dominio.Entidades.ServiciosExtras", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ServiciosExtras");
                });

            modelBuilder.Entity("lib_dominio.Entidades.Tareas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Empleado")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Finca")
                        .HasColumnType("int");

                    b.Property<int?>("_EmpleadoId")
                        .HasColumnType("int");

                    b.Property<int?>("_FincaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("_EmpleadoId");

                    b.HasIndex("_FincaId");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("lib_dominio.Entidades.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("lib_dominio.Entidades.Auditorias", b =>
                {
                    b.HasOne("lib_dominio.Entidades.Usuarios", "_Usuario")
                        .WithMany()
                        .HasForeignKey("_UsuarioId");

                    b.Navigation("_Usuario");
                });

            modelBuilder.Entity("lib_dominio.Entidades.Inventarios", b =>
                {
                    b.HasOne("lib_dominio.Entidades.Fincas", "_Finca")
                        .WithMany()
                        .HasForeignKey("_FincaId");

                    b.Navigation("_Finca");
                });

            modelBuilder.Entity("lib_dominio.Entidades.Mantenimientos", b =>
                {
                    b.HasOne("lib_dominio.Entidades.Fincas", "_Finca")
                        .WithMany()
                        .HasForeignKey("_FincaId");

                    b.Navigation("_Finca");
                });

            modelBuilder.Entity("lib_dominio.Entidades.Pagos", b =>
                {
                    b.HasOne("lib_dominio.Entidades.Reservas", "_Reserva")
                        .WithMany()
                        .HasForeignKey("_ReservaId");

                    b.Navigation("_Reserva");
                });

            modelBuilder.Entity("lib_dominio.Entidades.ReservaPromociones", b =>
                {
                    b.HasOne("lib_dominio.Entidades.Promociones", "_Promocion")
                        .WithMany()
                        .HasForeignKey("_PromocionId");

                    b.HasOne("lib_dominio.Entidades.Reservas", "_Reserva")
                        .WithMany()
                        .HasForeignKey("_ReservaId");

                    b.Navigation("_Promocion");

                    b.Navigation("_Reserva");
                });

            modelBuilder.Entity("lib_dominio.Entidades.ReservaServicios", b =>
                {
                    b.HasOne("lib_dominio.Entidades.Reservas", "_Reserva")
                        .WithMany()
                        .HasForeignKey("_ReservaId");

                    b.HasOne("lib_dominio.Entidades.ServiciosExtras", "_Servicio")
                        .WithMany()
                        .HasForeignKey("_ServicioId");

                    b.Navigation("_Reserva");

                    b.Navigation("_Servicio");
                });

            modelBuilder.Entity("lib_dominio.Entidades.Reservas", b =>
                {
                    b.HasOne("lib_dominio.Entidades.Clientes", "_Cliente")
                        .WithMany()
                        .HasForeignKey("_ClienteId");

                    b.HasOne("lib_dominio.Entidades.Fincas", "_Finca")
                        .WithMany()
                        .HasForeignKey("_FincaId");

                    b.Navigation("_Cliente");

                    b.Navigation("_Finca");
                });

            modelBuilder.Entity("lib_dominio.Entidades.Reseñas", b =>
                {
                    b.HasOne("lib_dominio.Entidades.Clientes", "_Cliente")
                        .WithMany()
                        .HasForeignKey("_ClienteId");

                    b.HasOne("lib_dominio.Entidades.Fincas", "_Finca")
                        .WithMany()
                        .HasForeignKey("_FincaId");

                    b.Navigation("_Cliente");

                    b.Navigation("_Finca");
                });

            modelBuilder.Entity("lib_dominio.Entidades.Tareas", b =>
                {
                    b.HasOne("lib_dominio.Entidades.Empleados", "_Empleado")
                        .WithMany()
                        .HasForeignKey("_EmpleadoId");

                    b.HasOne("lib_dominio.Entidades.Fincas", "_Finca")
                        .WithMany()
                        .HasForeignKey("_FincaId");

                    b.Navigation("_Empleado");

                    b.Navigation("_Finca");
                });
#pragma warning restore 612, 618
        }
    }
}
